### ISSUE TITLE
Codeblaze as a library...

### ISSUE THREAD

**Issue by EasyG0ing1** [omegaui/codeblaze#7]
Hello,

I've been working on [this project](https://github.com/RedmondSims/GistFX) off and on (more off than on lately) and it uses MonacoFX for the code editor, but I'm really not happy with it at all and have been looking for something to replace it with and I just found this project and I cloned it and ran it and REALLY like what you've done here. The aesthetics are solid and the functionality is solid and it can be themed etc.

So I'm wondering ... if I wrote an interface (which would be really just a class that would have the features that I would want if this project were a library) ... would you be willing to hook the methods in that interface into your project so that I could use the code editor in my project?

Thanks,

Mike

**Comment by omegaui** [comment]
Sorry for the late reply!
Of Course, Yes.
The entire core is built on Swing.
The Core UI is already separated [here](https://github.com/omegaui/omegaui-library)
List the methods or UI elements you want to have as a library and I will generalize the code.

**Comment by EasyG0ing1** [comment]
Awesome!

I don't need a lot, the getDocument method is really the biggest part of what I need. I just need it to be whatever you have that is the code editor and I need to be able to place that object inside a JavaFX Parent. Once I have that object, I then just bind a TextProperty from a class that changes as the user selects different Gist files to work on.

So the way I'm thinking ... is that you could write a class that uses this interface that provides the capability I'm looking for. Maybe even put that class in an exposed Package ... like maybe ```omegaui.codeblaze.library.Document``` or something along those lines.

This is really all the functionality I need

```Java
public interface CodeblazeInterface {

	public javafx.scene.control.TextArea getDocument();
	/*
	This would return an object of whatever type you can provide, where it is a JavaFX object that can be
	placed in a JavaFX Parent like a VBOx, HBox, AnchorPane etc.
	 */

	public void bindTextProperty(StringProperty stringProperty);
	/*
	This would take the StringProperty bean that I pass it, and it would bind it to the textProperty
	of the Document object.
	 */

	public void setTheme();
	/*
	However you theme the object, you would need to tell me what it is I need to provide.
	 */

	public void setLanguage(String language);
	/*
	I usually just extract the filename extension and pass it to the class which then switches
	to that language
	 */

	public void setFont(Font font);

	public void setFontSize(int size);

	public int getFontSize();

	public Font getFont();

	public String getThene();
	/*
	I just put String as the return type, but if you have a theme object that you use, then specify that as the return type
	 */

	public String getLanguage();

}
```

**Comment by omegaui** [comment]
I think, you only need the editor part, Right?
If thats the case, then,
The Editor codeblaze utilizes is bobbylight's [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea).

I myself have contributed to the project many times.
A thing more,
Since, you are using JavaFX at the core,
And the editor is actually a Java Swing Component,
So, you need to wrap it inside the `SwingNode`.
There's a fall here, wrapping RSyntaxTextArea inside JavaFX causes most of the funtionalities to fail to work properly, most importantly AnitAliasing will fail to work and the editor will look too ugly to see.

I suggest you to use Swing instead of JavaFX for your project if possible.

**Comment by EasyG0ing1** [comment]
I was under the impression that Swing was not that widely used anymore. JavaFX being far more aesthetically pleasing than Swing ... in general.

**Comment by omegaui** [comment]
Here's an example of leveraging the beauty and stabilty Swing can reach to [💪 Here](https://github.com/omegaui/omegaide).

> Swing is not used anymore...

Well, all of jetbrains IDE are written and maintained till date, in Java Swing.

**Comment by EasyG0ing1** [comment]
> Here's an example of leveraging the beauty and stabilty Swing can reach to [💪 Here](https://github.com/omegaui/omegaide).
> 
> > Swing is not used anymore...
> 
> Well, all of jetbrains IDE are written and maintained till date, in Java Swing.

That's interesting, I did not know that. I have little experience with Swing in general, though it doesn't seem too difficult ...  certainly, I've never written a UI in Swing before.

**Comment by EasyG0ing1** [comment]
It's a shame that JavaFX was not an evolution of Swing ... it would have eliminated incompatibility and kept the general method of object usage within the same general syntax.

**Comment by omegaui** [comment]
> It's a shame that JavaFX was not an evolution of Swing ... it would have eliminated incompatibility and kept the general method of object usage within the same general syntax. 

Yes you are entirely right,
If that was real,
Just imagine the flexibility of UI that can be achieved.
